[package]
name = "daemonize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.14"
lettre = "0.10.0-rc.7"
libc = "0.2"
tokio = "1"
